### ISSUE TITLE
How to obtain image data based on mask and crop each object

### ISSUE THREAD

**Issue by hktalent** [Hyuto/yolov8-seg-tfjs#3]
How to obtain image data based on mask and crop each object? Thank you very much

**Comment by Hyuto** [comment]
Hello,

I doubt we can do a lot of these type in JS, but if you want to get the final mask it's on

https://github.com/Hyuto/yolov8-seg-tfjs/blob/4d5c0c216ecf0a9eb8313ef4b9a18de831d49068/src/utils/detect.js#L144 

`mask` variable contains boolean typed tensor for masking you can crop each object from image using that mask. I don't really know how to do it on JS but in python it's easily done using something like numpy, etc.

**Comment by hktalent** [comment]
@Hyuto sorry，😭I'm not familiar with tfjs, can you teach me?

For example, I would like to see cars and people cropped out

**Comment by hktalent** [comment]
I know Python is easier, but I hope the web can do this job to avoid putting all the computational pressure on the backend
